#!/bin/sh
ffmpeg \
-user_agent "$1" \
-reconnect 1 \
-reconnect_at_eof 1 \
-reconnect_streamed 1 \
-reconnect_delay_max 5 \
-multiple_requests 1 \
-seekable 0 \
-fflags +discardcorrupt+genpts+igndts \
-probesize 512K \
-analyzeduration 1M \
-i "$2" \
-map 0:v:0? \
-map 0:a? \
-sn -dn \
-c:v h264_nvenc \
-preset p4 \
-profile:v high \
-pix_fmt yuv420p \
-rc cbr \
-b:v 8M \
-maxrate 8M \
-bufsize 16M \
-g 60 \
-keyint_min 60 \
-sc_threshold 0 \
-c:a aac \
-b:a 384k \
-ac 2 \
-async 1 \
-mpegts_copyts 0 \
-avoid_negative_ts make_zero \
-muxdelay 0 \
-muxpreload 0 \
-max_muxing_queue_size 4096 \
-flush_packets 1 \
-mpegts_flags +pat_pmt_at_frames+resend_headers+initial_discontinuity \
-f mpegts pipe:1 | \
HOME=/home/dispatch cvlc \
-I dummy \
--no-lua \
--no-auto-preparse \
--no-dbus \
--no-interact \
--no-stats \
--aout adummy \
--vout vdummy \
--no-sout-all \
--sout-keep \
--network-caching 3000 \
--sout-mux-caching 1500 \
--adaptive-logic=highest \
--sout="#std{access=file,mux=ts,dst=-}" \
fd://0
